# Generated by Django 6.0 on 2026-01-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiBullsi', '0002_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
